spring.application.name=SmartMall

spring.datasource.url=jdbc:mysql://localhost:3306/smartmall?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
spring.datasource.username=root
spring.datasource.password=Ljb456799
